name: external_link_account_modal
description: An easy-to-use widget that complies with Apple's External Link Account requirements for reader apps
version: 1.0.0
homepage: https://github.com/ArvidNy/external_link_account_modal

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  url_launcher: ^6.1.5
  devicelocale: ^0.5.4
  device_info_plus: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ExternalLinkAccountModalPlugin